In [1]:
import pandas as pd 
from sklearn.utils import resample

In [38]:
## Dataset 
data = {
    'feature1': [1,2,3,4,5,6],
    'feature2': [10,20,30,40,50,60], 
    'index': [0,0,0,0,1,1]
}

In [39]:
df= pd.DataFrame(data)

In [40]:
df['index'].value_counts()

index
0    4
1    2
Name: count, dtype: int64

In [41]:
# Separate majority and minority classes
df_majority = df[df.index == 0] 
df_minority = df[df.index == 1]

In [33]:
# Upsample minority class
df_minority_upsample = resample(
    df_minority, 
    replace = True, 
    n_samples=len(df_majority), 
    random_state=42
)

In [34]:
# Combine majority + upsampled minority 
df_upsampled = pd.concat([df_majority,df_minority_upsample])

In [35]:
df_upsampled

   feature1  feature2  index
0         1        10      0
1         2        20      0

In [36]:
df

   feature1  feature2  index
0         1        10      0
1         2        20      0
2         3        30      0
3         4        40      0
4         5        50      1
5         6        60      1

In [37]:
df_upsampled['index'].value_counts()

index
0    2
Name: count, dtype: int64